name: Backend CI/CD pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_LAMBDA_OBJECT_ANALYSIS: ${{ secrets.AWS_LAMBDA_OBJECT_ANALYSIS }}
      AWS_LAMBDA_CELEBRITY_RECOGNITION: ${{ secrets.AWS_LAMBDA_CELEBRITY_RECOGNITION }}
      AWS_S3_INPUT_BUCKET: ${{secrets.AWS_S3_INPUT_BUCKET}}
      AWS_S3_OUTPUT_BUCKET: ${{secrets.AWS_S3_OUTPUT_BUCKET}}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: LambdaControllerTests
      run: dotnet test --filter FullyQualifiedName~Detectify.Tests.LambdaControllerTests --no-build --verbosity normal
    - name: S3ControllerTests
      run: dotnet test --filter FullyQualifiedName~Detectify.Tests.S3ControllerTests --no-build --verbosity normal